# Generated by Django 5.1.5 on 2025-01-31 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={"ordering": ["done_or_not", "created_at"]},
        ),
    ]
