# Generated by Django 5.1.5 on 2025-01-31 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_alter_task_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={"ordering": ["done_or_not", "-created_at"]},
        ),
    ]
